### ISSUE TITLE
undefined method `mongoid_filter_form_object_path' 

### ISSUE THREAD

**Issue by ishwinder** [flexoid/mongoid_filter#3]
The issue occurs on building the form with the module in the view.

Where @bookings is defined in controller by :
@bookings = Booking.where(status: :created).filter_by(params[:search])

<%= form_for @bookings.filter_form_object, as: :search do |f| %>

**Comment by flexoid** [comment]
Hi. For now just try to set URL manually like this, it should help:

```
<%= form_for @bookings.filter_form_object, as: :search, url: bookings_path do |f| %>
```

I'll fix this later.
